/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse20014Areacodes = factory(root.FaxtoRestApiClientForJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20014Areacodes model module.
   * @module model/InlineResponse20014Areacodes
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20014Areacodes</code>.
   * @alias module:model/InlineResponse20014Areacodes
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse20014Areacodes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20014Areacodes} obj Optional instance to populate.
   * @return {module:model/InlineResponse20014Areacodes} The populated <code>InlineResponse20014Areacodes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('country_code')) {
        obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
      }
      if (data.hasOwnProperty('state_id')) {
        obj['state_id'] = ApiClient.convertToType(data['state_id'], 'Number');
      }
      if (data.hasOwnProperty('area_code')) {
        obj['area_code'] = ApiClient.convertToType(data['area_code'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} country_code
   */
  exports.prototype['country_code'] = undefined;
  /**
   * @member {Number} state_id
   */
  exports.prototype['state_id'] = undefined;
  /**
   * @member {String} area_code
   */
  exports.prototype['area_code'] = undefined;



  return exports;
}));


