/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse20016Data = factory(root.FaxtoRestApiClientForJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20016Data model module.
   * @module model/InlineResponse20016Data
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20016Data</code>.
   * @alias module:model/InlineResponse20016Data
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>InlineResponse20016Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20016Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse20016Data} The populated <code>InlineResponse20016Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('did_id')) {
        obj['did_id'] = ApiClient.convertToType(data['did_id'], 'Number');
      }
      if (data.hasOwnProperty('did_group_id')) {
        obj['did_group_id'] = ApiClient.convertToType(data['did_group_id'], 'Number');
      }
      if (data.hasOwnProperty('country_code')) {
        obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
      }
      if (data.hasOwnProperty('city_name')) {
        obj['city_name'] = ApiClient.convertToType(data['city_name'], 'String');
      }
      if (data.hasOwnProperty('area_code')) {
        obj['area_code'] = ApiClient.convertToType(data['area_code'], 'String');
      }
      if (data.hasOwnProperty('number')) {
        obj['number'] = ApiClient.convertToType(data['number'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('trunk_id')) {
        obj['trunk_id'] = ApiClient.convertToType(data['trunk_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} did_id
   */
  exports.prototype['did_id'] = undefined;
  /**
   * @member {Number} did_group_id
   */
  exports.prototype['did_group_id'] = undefined;
  /**
   * @member {String} country_code
   */
  exports.prototype['country_code'] = undefined;
  /**
   * @member {String} city_name
   */
  exports.prototype['city_name'] = undefined;
  /**
   * @member {String} area_code
   */
  exports.prototype['area_code'] = undefined;
  /**
   * @member {String} number
   */
  exports.prototype['number'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} trunk_id
   */
  exports.prototype['trunk_id'] = undefined;



  return exports;
}));


