/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2003Created'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2003Created'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse2003History = factory(root.FaxtoRestApiClientForJavascript.ApiClient, root.FaxtoRestApiClientForJavascript.InlineResponse2003Created);
  }
}(this, function(ApiClient, InlineResponse2003Created) {
  'use strict';




  /**
   * The InlineResponse2003History model module.
   * @module model/InlineResponse2003History
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2003History</code>.
   * @alias module:model/InlineResponse2003History
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>InlineResponse2003History</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003History} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003History} The populated <code>InlineResponse2003History</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = InlineResponse2003Created.constructFromObject(data['created']);
      }
      if (data.hasOwnProperty('document_id')) {
        obj['document_id'] = ApiClient.convertToType(data['document_id'], 'Number');
      }
      if (data.hasOwnProperty('document')) {
        obj['document'] = ApiClient.convertToType(data['document'], 'String');
      }
      if (data.hasOwnProperty('recipient')) {
        obj['recipient'] = ApiClient.convertToType(data['recipient'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/InlineResponse2003Created} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {Number} document_id
   */
  exports.prototype['document_id'] = undefined;
  /**
   * @member {String} document
   */
  exports.prototype['document'] = undefined;
  /**
   * @member {String} recipient
   */
  exports.prototype['recipient'] = undefined;
  /**
   * The status of the fax job
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


