/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse2009 = factory(root.FaxtoRestApiClientForJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2009 model module.
   * @module model/InlineResponse2009
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2009</code>.
   * @alias module:model/InlineResponse2009
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>InlineResponse2009</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009} The populated <code>InlineResponse2009</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
      if (data.hasOwnProperty('created_date')) {
        obj['created_date'] = ApiClient.convertToType(data['created_date'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('filename')) {
        obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
      }
      if (data.hasOwnProperty('orig_filename')) {
        obj['orig_filename'] = ApiClient.convertToType(data['orig_filename'], 'String');
      }
      if (data.hasOwnProperty('preview_file')) {
        obj['preview_file'] = ApiClient.convertToType(data['preview_file'], 'String');
      }
      if (data.hasOwnProperty('preview_image')) {
        obj['preview_image'] = ApiClient.convertToType(data['preview_image'], 'String');
      }
      if (data.hasOwnProperty('preview_in_storage')) {
        obj['preview_in_storage'] = ApiClient.convertToType(data['preview_in_storage'], 'Number');
      }
      if (data.hasOwnProperty('file_extension')) {
        obj['file_extension'] = ApiClient.convertToType(data['file_extension'], 'String');
      }
      if (data.hasOwnProperty('filename_uploaded')) {
        obj['filename_uploaded'] = ApiClient.convertToType(data['filename_uploaded'], 'String');
      }
      if (data.hasOwnProperty('filesize')) {
        obj['filesize'] = ApiClient.convertToType(data['filesize'], 'String');
      }
      if (data.hasOwnProperty('s3')) {
        obj['s3'] = ApiClient.convertToType(data['s3'], 'Number');
      }
      if (data.hasOwnProperty('server_document_id')) {
        obj['server_document_id'] = ApiClient.convertToType(data['server_document_id'], 'Number');
      }
      if (data.hasOwnProperty('team_user_id')) {
        obj['team_user_id'] = ApiClient.convertToType(data['team_user_id'], 'Number');
      }
      if (data.hasOwnProperty('total_pages')) {
        obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * @member {Date} created_date
   */
  exports.prototype['created_date'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} filename
   */
  exports.prototype['filename'] = undefined;
  /**
   * @member {String} orig_filename
   */
  exports.prototype['orig_filename'] = undefined;
  /**
   * @member {String} preview_file
   */
  exports.prototype['preview_file'] = undefined;
  /**
   * @member {String} preview_image
   */
  exports.prototype['preview_image'] = undefined;
  /**
   * @member {Number} preview_in_storage
   */
  exports.prototype['preview_in_storage'] = undefined;
  /**
   * @member {String} file_extension
   */
  exports.prototype['file_extension'] = undefined;
  /**
   * @member {String} filename_uploaded
   */
  exports.prototype['filename_uploaded'] = undefined;
  /**
   * @member {String} filesize
   */
  exports.prototype['filesize'] = undefined;
  /**
   * @member {Number} s3
   */
  exports.prototype['s3'] = undefined;
  /**
   * @member {Number} server_document_id
   */
  exports.prototype['server_document_id'] = undefined;
  /**
   * @member {Number} team_user_id
   */
  exports.prototype['team_user_id'] = undefined;
  /**
   * @member {Number} total_pages
   */
  exports.prototype['total_pages'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


