/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2003Created'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2003Created'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse2004Inbox = factory(root.FaxtoRestApiClientForJavascript.ApiClient, root.FaxtoRestApiClientForJavascript.InlineResponse2003Created);
  }
}(this, function(ApiClient, InlineResponse2003Created) {
  'use strict';




  /**
   * The InlineResponse2004Inbox model module.
   * @module model/InlineResponse2004Inbox
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2004Inbox</code>.
   * @alias module:model/InlineResponse2004Inbox
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>InlineResponse2004Inbox</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2004Inbox} obj Optional instance to populate.
   * @return {module:model/InlineResponse2004Inbox} The populated <code>InlineResponse2004Inbox</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('did_id')) {
        obj['did_id'] = ApiClient.convertToType(data['did_id'], 'Number');
      }
      if (data.hasOwnProperty('filename')) {
        obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
      }
      if (data.hasOwnProperty('filesize')) {
        obj['filesize'] = ApiClient.convertToType(data['filesize'], 'String');
      }
      if (data.hasOwnProperty('number')) {
        obj['number'] = ApiClient.convertToType(data['number'], 'String');
      }
      if (data.hasOwnProperty('sender')) {
        obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
      }
      if (data.hasOwnProperty('total_pages')) {
        obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = InlineResponse2003Created.constructFromObject(data['created_at']);
      }
      if (data.hasOwnProperty('preview_file')) {
        obj['preview_file'] = ApiClient.convertToType(data['preview_file'], 'String');
      }
      if (data.hasOwnProperty('file_url')) {
        obj['file_url'] = ApiClient.convertToType(data['file_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} did_id
   */
  exports.prototype['did_id'] = undefined;
  /**
   * @member {String} filename
   */
  exports.prototype['filename'] = undefined;
  /**
   * @member {String} filesize
   */
  exports.prototype['filesize'] = undefined;
  /**
   * @member {String} number
   */
  exports.prototype['number'] = undefined;
  /**
   * @member {String} sender
   */
  exports.prototype['sender'] = undefined;
  /**
   * @member {Number} total_pages
   */
  exports.prototype['total_pages'] = undefined;
  /**
   * @member {module:model/InlineResponse2003Created} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} preview_file
   */
  exports.prototype['preview_file'] = undefined;
  /**
   * @member {String} file_url
   */
  exports.prototype['file_url'] = undefined;



  return exports;
}));


