/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse20017Numbers = factory(root.FaxtoRestApiClientForJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20017Numbers model module.
   * @module model/InlineResponse20017Numbers
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20017Numbers</code>.
   * @alias module:model/InlineResponse20017Numbers
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>InlineResponse20017Numbers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20017Numbers} obj Optional instance to populate.
   * @return {module:model/InlineResponse20017Numbers} The populated <code>InlineResponse20017Numbers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('order_reference')) {
        obj['order_reference'] = ApiClient.convertToType(data['order_reference'], 'String');
      }
      if (data.hasOwnProperty('country_code')) {
        obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('city_name')) {
        obj['city_name'] = ApiClient.convertToType(data['city_name'], 'String');
      }
      if (data.hasOwnProperty('area_code')) {
        obj['area_code'] = ApiClient.convertToType(data['area_code'], 'String');
      }
      if (data.hasOwnProperty('did_group_id')) {
        obj['did_group_id'] = ApiClient.convertToType(data['did_group_id'], 'Number');
      }
      if (data.hasOwnProperty('did_number')) {
        obj['did_number'] = ApiClient.convertToType(data['did_number'], 'String');
      }
      if (data.hasOwnProperty('expiration_date')) {
        obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} order_reference
   */
  exports.prototype['order_reference'] = undefined;
  /**
   * @member {String} country_code
   */
  exports.prototype['country_code'] = undefined;
  /**
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {String} city_name
   */
  exports.prototype['city_name'] = undefined;
  /**
   * @member {String} area_code
   */
  exports.prototype['area_code'] = undefined;
  /**
   * @member {Number} did_group_id
   */
  exports.prototype['did_group_id'] = undefined;
  /**
   * @member {String} did_number
   */
  exports.prototype['did_number'] = undefined;
  /**
   * @member {Date} expiration_date
   */
  exports.prototype['expiration_date'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


