/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse20012Data = factory(root.FaxtoRestApiClientForJavascript.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20012Data model module.
   * @module model/InlineResponse20012Data
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20012Data</code>.
   * @alias module:model/InlineResponse20012Data
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>InlineResponse20012Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20012Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse20012Data} The populated <code>InlineResponse20012Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('a2_code')) {
        obj['a2_code'] = ApiClient.convertToType(data['a2_code'], 'String');
      }
      if (data.hasOwnProperty('dial_code')) {
        obj['dial_code'] = ApiClient.convertToType(data['dial_code'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * @member {String} a2_code
   */
  exports.prototype['a2_code'] = undefined;
  /**
   * @member {Number} dial_code
   */
  exports.prototype['dial_code'] = undefined;



  return exports;
}));


