/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2004MetaPagination'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2004MetaPagination'));
  } else {
    // Browser globals (root is window)
    if (!root.FaxtoRestApiClientForJavascript) {
      root.FaxtoRestApiClientForJavascript = {};
    }
    root.FaxtoRestApiClientForJavascript.InlineResponse2004Meta = factory(root.FaxtoRestApiClientForJavascript.ApiClient, root.FaxtoRestApiClientForJavascript.InlineResponse2004MetaPagination);
  }
}(this, function(ApiClient, InlineResponse2004MetaPagination) {
  'use strict';




  /**
   * The InlineResponse2004Meta model module.
   * @module model/InlineResponse2004Meta
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2004Meta</code>.
   * Contains the paginations links
   * @alias module:model/InlineResponse2004Meta
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>InlineResponse2004Meta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2004Meta} obj Optional instance to populate.
   * @return {module:model/InlineResponse2004Meta} The populated <code>InlineResponse2004Meta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pagination')) {
        obj['pagination'] = InlineResponse2004MetaPagination.constructFromObject(data['pagination']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse2004MetaPagination} pagination
   */
  exports.prototype['pagination'] = undefined;



  return exports;
}));


