/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FaxtoRestApiClientForJavascript);
  }
}(this, function(expect, FaxtoRestApiClientForJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2004Inbox', function() {
    it('should create an instance of InlineResponse2004Inbox', function() {
      // uncomment below and update the code to test InlineResponse2004Inbox
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be.a(FaxtoRestApiClientForJavascript.InlineResponse2004Inbox);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property didId (base name: "did_id")', function() {
      // uncomment below and update the code to test the property didId
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property filename (base name: "filename")', function() {
      // uncomment below and update the code to test the property filename
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property filesize (base name: "filesize")', function() {
      // uncomment below and update the code to test the property filesize
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property sender (base name: "sender")', function() {
      // uncomment below and update the code to test the property sender
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property totalPages (base name: "total_pages")', function() {
      // uncomment below and update the code to test the property totalPages
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property previewFile (base name: "preview_file")', function() {
      // uncomment below and update the code to test the property previewFile
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

    it('should have the property fileUrl (base name: "file_url")', function() {
      // uncomment below and update the code to test the property fileUrl
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse2004Inbox();
      //expect(instance).to.be();
    });

  });

}));
