/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FaxtoRestApiClientForJavascript);
  }
}(this, function(expect, FaxtoRestApiClientForJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FaxtoRestApiClientForJavascript.InlineResponse20012Data();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20012Data', function() {
    it('should create an instance of InlineResponse20012Data', function() {
      // uncomment below and update the code to test InlineResponse20012Data
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20012Data();
      //expect(instance).to.be.a(FaxtoRestApiClientForJavascript.InlineResponse20012Data);
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20012Data();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20012Data();
      //expect(instance).to.be();
    });

    it('should have the property a2Code (base name: "a2_code")', function() {
      // uncomment below and update the code to test the property a2Code
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20012Data();
      //expect(instance).to.be();
    });

    it('should have the property dialCode (base name: "dial_code")', function() {
      // uncomment below and update the code to test the property dialCode
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20012Data();
      //expect(instance).to.be();
    });

  });

}));
