/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FaxtoRestApiClientForJavascript);
  }
}(this, function(expect, FaxtoRestApiClientForJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FaxtoRestApiClientForJavascript.InlineResponse20015Data();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20015Data', function() {
    it('should create an instance of InlineResponse20015Data', function() {
      // uncomment below and update the code to test InlineResponse20015Data
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20015Data();
      //expect(instance).to.be.a(FaxtoRestApiClientForJavascript.InlineResponse20015Data);
    });

    it('should have the property didGroupId (base name: "did_group_id")', function() {
      // uncomment below and update the code to test the property didGroupId
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20015Data();
      //expect(instance).to.be();
    });

    it('should have the property areaCode (base name: "area_code")', function() {
      // uncomment below and update the code to test the property areaCode
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20015Data();
      //expect(instance).to.be();
    });

    it('should have the property cityName (base name: "city_name")', function() {
      // uncomment below and update the code to test the property cityName
      //var instance = new FaxtoRestApiClientForJavascript.InlineResponse20015Data();
      //expect(instance).to.be();
    });

  });

}));
