/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/InlineResponse20010', 'model/InlineResponse20011', 'model/InlineResponse20012', 'model/InlineResponse20012Data', 'model/InlineResponse20013', 'model/InlineResponse20013States', 'model/InlineResponse20014', 'model/InlineResponse20014Areacodes', 'model/InlineResponse20015', 'model/InlineResponse20015Data', 'model/InlineResponse20016', 'model/InlineResponse20016Data', 'model/InlineResponse20017', 'model/InlineResponse20017Numbers', 'model/InlineResponse2002', 'model/InlineResponse2003', 'model/InlineResponse2003Created', 'model/InlineResponse2003History', 'model/InlineResponse2004', 'model/InlineResponse2004Inbox', 'model/InlineResponse2004Meta', 'model/InlineResponse2004MetaPagination', 'model/InlineResponse2004MetaPaginationLinks', 'model/InlineResponse2005', 'model/InlineResponse2006', 'model/InlineResponse2007', 'model/InlineResponse2008', 'model/InlineResponse2008Files', 'model/InlineResponse2009', 'model/InlineResponse400', 'api/FaxReceivingApi', 'api/FaxSendingApi', 'api/UserApi', 'api/UserManagementApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse20010'), require('./model/InlineResponse20011'), require('./model/InlineResponse20012'), require('./model/InlineResponse20012Data'), require('./model/InlineResponse20013'), require('./model/InlineResponse20013States'), require('./model/InlineResponse20014'), require('./model/InlineResponse20014Areacodes'), require('./model/InlineResponse20015'), require('./model/InlineResponse20015Data'), require('./model/InlineResponse20016'), require('./model/InlineResponse20016Data'), require('./model/InlineResponse20017'), require('./model/InlineResponse20017Numbers'), require('./model/InlineResponse2002'), require('./model/InlineResponse2003'), require('./model/InlineResponse2003Created'), require('./model/InlineResponse2003History'), require('./model/InlineResponse2004'), require('./model/InlineResponse2004Inbox'), require('./model/InlineResponse2004Meta'), require('./model/InlineResponse2004MetaPagination'), require('./model/InlineResponse2004MetaPaginationLinks'), require('./model/InlineResponse2005'), require('./model/InlineResponse2006'), require('./model/InlineResponse2007'), require('./model/InlineResponse2008'), require('./model/InlineResponse2008Files'), require('./model/InlineResponse2009'), require('./model/InlineResponse400'), require('./api/FaxReceivingApi'), require('./api/FaxSendingApi'), require('./api/UserApi'), require('./api/UserManagementApi'));
  }
}(function(ApiClient, InlineResponse200, InlineResponse2001, InlineResponse20010, InlineResponse20011, InlineResponse20012, InlineResponse20012Data, InlineResponse20013, InlineResponse20013States, InlineResponse20014, InlineResponse20014Areacodes, InlineResponse20015, InlineResponse20015Data, InlineResponse20016, InlineResponse20016Data, InlineResponse20017, InlineResponse20017Numbers, InlineResponse2002, InlineResponse2003, InlineResponse2003Created, InlineResponse2003History, InlineResponse2004, InlineResponse2004Inbox, InlineResponse2004Meta, InlineResponse2004MetaPagination, InlineResponse2004MetaPaginationLinks, InlineResponse2005, InlineResponse2006, InlineResponse2007, InlineResponse2008, InlineResponse2008Files, InlineResponse2009, InlineResponse400, FaxReceivingApi, FaxSendingApi, UserApi, UserManagementApi) {
  'use strict';

  /**
   * This_is_Fax_to_REST_API_client_for_Javascript_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var FaxtoRestApiClientForJavascript = require('index'); // See note below*.
   * var xxxSvc = new FaxtoRestApiClientForJavascript.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new FaxtoRestApiClientForJavascript.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new FaxtoRestApiClientForJavascript.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new FaxtoRestApiClientForJavascript.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010: InlineResponse20010,
    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011: InlineResponse20011,
    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012: InlineResponse20012,
    /**
     * The InlineResponse20012Data model constructor.
     * @property {module:model/InlineResponse20012Data}
     */
    InlineResponse20012Data: InlineResponse20012Data,
    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013: InlineResponse20013,
    /**
     * The InlineResponse20013States model constructor.
     * @property {module:model/InlineResponse20013States}
     */
    InlineResponse20013States: InlineResponse20013States,
    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014: InlineResponse20014,
    /**
     * The InlineResponse20014Areacodes model constructor.
     * @property {module:model/InlineResponse20014Areacodes}
     */
    InlineResponse20014Areacodes: InlineResponse20014Areacodes,
    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015: InlineResponse20015,
    /**
     * The InlineResponse20015Data model constructor.
     * @property {module:model/InlineResponse20015Data}
     */
    InlineResponse20015Data: InlineResponse20015Data,
    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016: InlineResponse20016,
    /**
     * The InlineResponse20016Data model constructor.
     * @property {module:model/InlineResponse20016Data}
     */
    InlineResponse20016Data: InlineResponse20016Data,
    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017: InlineResponse20017,
    /**
     * The InlineResponse20017Numbers model constructor.
     * @property {module:model/InlineResponse20017Numbers}
     */
    InlineResponse20017Numbers: InlineResponse20017Numbers,
    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002: InlineResponse2002,
    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003: InlineResponse2003,
    /**
     * The InlineResponse2003Created model constructor.
     * @property {module:model/InlineResponse2003Created}
     */
    InlineResponse2003Created: InlineResponse2003Created,
    /**
     * The InlineResponse2003History model constructor.
     * @property {module:model/InlineResponse2003History}
     */
    InlineResponse2003History: InlineResponse2003History,
    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004: InlineResponse2004,
    /**
     * The InlineResponse2004Inbox model constructor.
     * @property {module:model/InlineResponse2004Inbox}
     */
    InlineResponse2004Inbox: InlineResponse2004Inbox,
    /**
     * The InlineResponse2004Meta model constructor.
     * @property {module:model/InlineResponse2004Meta}
     */
    InlineResponse2004Meta: InlineResponse2004Meta,
    /**
     * The InlineResponse2004MetaPagination model constructor.
     * @property {module:model/InlineResponse2004MetaPagination}
     */
    InlineResponse2004MetaPagination: InlineResponse2004MetaPagination,
    /**
     * The InlineResponse2004MetaPaginationLinks model constructor.
     * @property {module:model/InlineResponse2004MetaPaginationLinks}
     */
    InlineResponse2004MetaPaginationLinks: InlineResponse2004MetaPaginationLinks,
    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005: InlineResponse2005,
    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006: InlineResponse2006,
    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007: InlineResponse2007,
    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008: InlineResponse2008,
    /**
     * The InlineResponse2008Files model constructor.
     * @property {module:model/InlineResponse2008Files}
     */
    InlineResponse2008Files: InlineResponse2008Files,
    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009: InlineResponse2009,
    /**
     * The InlineResponse400 model constructor.
     * @property {module:model/InlineResponse400}
     */
    InlineResponse400: InlineResponse400,
    /**
     * The FaxReceivingApi service constructor.
     * @property {module:api/FaxReceivingApi}
     */
    FaxReceivingApi: FaxReceivingApi,
    /**
     * The FaxSendingApi service constructor.
     * @property {module:api/FaxSendingApi}
     */
    FaxSendingApi: FaxSendingApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi,
    /**
     * The UserManagementApi service constructor.
     * @property {module:api/UserManagementApi}
     */
    UserManagementApi: UserManagementApi
  };

  return exports;
}));
