/**
 * Fax.to REST API client for Javascript
 * This is Fax.to REST API client for Javascript.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FaxtoRestApiClientForJavascript);
  }
}(this, function(expect, FaxtoRestApiClientForJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FaxtoRestApiClientForJavascript.FaxSendingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FaxSendingApi', function() {
    describe('faxDocumentIdCostsGet', function() {
      it('should call faxDocumentIdCostsGet successfully', function(done) {
        //uncomment below and update the code to test faxDocumentIdCostsGet
        //instance.faxDocumentIdCostsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('faxHistoryGet', function() {
      it('should call faxHistoryGet successfully', function(done) {
        //uncomment below and update the code to test faxHistoryGet
        //instance.faxHistoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('faxJobIdStatusGet', function() {
      it('should call faxJobIdStatusGet successfully', function(done) {
        //uncomment below and update the code to test faxJobIdStatusGet
        //instance.faxJobIdStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('faxPost', function() {
      it('should call faxPost successfully', function(done) {
        //uncomment below and update the code to test faxPost
        //instance.faxPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fileCleanGet', function() {
      it('should call fileCleanGet successfully', function(done) {
        //uncomment below and update the code to test fileCleanGet
        //instance.fileCleanGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fileGeneratePreviewGet', function() {
      it('should call fileGeneratePreviewGet successfully', function(done) {
        //uncomment below and update the code to test fileGeneratePreviewGet
        //instance.fileGeneratePreviewGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesDocumentIDDelete', function() {
      it('should call filesDocumentIDDelete successfully', function(done) {
        //uncomment below and update the code to test filesDocumentIDDelete
        //instance.filesDocumentIDDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesGet', function() {
      it('should call filesGet successfully', function(done) {
        //uncomment below and update the code to test filesGet
        //instance.filesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
